In [74]:
import os
import pandas as pd

In [75]:
# 1.Load data
df = pd.read_csv("mortgage_data.csv")

df

   Loan_ID    Borrower_Name  Loan_Amount  Interest_Rate Loan_Status
0     1001       John Smith     250000.0            6.5    Approved
1     1002        Sarah Lee     180000.0            5.9     Pending
2     1003              NaN     300000.0            7.1    Approved
3     1004      David Brown    -150000.0            6.2    Rejected
4     1005      Emily Davis     220000.0           25.0    Approved
5     1002        Sarah Lee     180000.0            5.9     Pending
6     1006  Michael Johnson          NaN            4.8    Approved
7     1007      Alice White     275000.0            NaN    Approved

In [76]:
# 2.Check missing values


print("\n---Count of missing values by column ---")
missing_values = df.isnull().sum()

missing_values

---Count of missing values by column ---

Loan_ID          0
Borrower_Name    1
Loan_Amount      1
Interest_Rate    1
Loan_Status      0
dtype: int64

In [77]:
# 3. Check duplicate rows

print("\n---Return duplicate rows ---")
duplicate_rows = df[df["Loan_ID"].duplicated(keep=False)]

duplicate_rows

---Return duplicate rows ---

   Loan_ID Borrower_Name  Loan_Amount  Interest_Rate Loan_Status
1     1002     Sarah Lee     180000.0            5.9     Pending
5     1002     Sarah Lee     180000.0            5.9     Pending

In [78]:
# 4.Check invalid loan amount

print("\n---Rows where Loan_Amount is missing or not greater than 0 ---")
invalid_loan_amount = df[(df["Loan_Amount"].isnull()) | (df["Loan_Amount"] <= 0)]

invalid_loan_amount

---Rows where Loan_Amount is missing or not greater than 0 ---

   Loan_ID    Borrower_Name  Loan_Amount  Interest_Rate Loan_Status
3     1004      David Brown    -150000.0            6.2    Rejected
6     1006  Michael Johnson          NaN            4.8    Approved

In [79]:
# 5.Check Invalid Interest Rate

print("\n---Rows where Interest_Rate is missing or outside 0 to 15---")
invalid_interest_rate = df[
        (df["Interest_Rate"].isnull()) |
        (df["Interest_Rate"] < 0) |
        (df["Interest_Rate"] > 15)
    ]

invalid_interest_rate

---Rows where Interest_Rate is missing or outside 0 to 15---

   Loan_ID Borrower_Name  Loan_Amount  Interest_Rate Loan_Status
4     1005   Emily Davis     220000.0           25.0    Approved
7     1007   Alice White     275000.0            NaN    Approved

In [80]:
# 6. Check missing or blank borrower names
print("\n---Rows where Borrower_Name is missing or blank---")
missing_borrower_name = df[(df["Borrower_Name"].isnull()) | (df["Borrower_Name"].astype(str).str.strip() == "")]

missing_borrower_name

---Rows where Borrower_Name is missing or blank---

   Loan_ID Borrower_Name  Loan_Amount  Interest_Rate Loan_Status
2     1003           NaN     300000.0            7.1    Approved

In [81]:
# 7. Check Invalid Loan status

print("\n---Rows where Loan_Status is not in allowed values---")
valid_statuses = ["Approved", "Pending", "Rejected"]
invalid_loan_status = df[~df["Loan_Status"].isin(valid_statuses)]

---Rows where Loan_Status is not in allowed values---

In [113]:
# 8. Calculate total issues

total_issues = (
    len(duplicate_rows) +
    len(invalid_loan_amount) + 
    len(invalid_interest_rate) + 
    len(missing_borrower_name) + 
    len(invalid_loan_status) +
    missing_values.sum()
)

total_issues

np.int64(10)

In [83]:
# 9. calculate data quality score

def calculate_data_quality_score(df, total_issues):
    total_rows = len(df)

    if total_rows == 0:
        return 0

    quality_score = 100 - ((total_issues / total_rows) * 100)
    return max(score, 0)

print(total_rows)
print(total_issues)
print(score)

8
10
-25.0

In [84]:
# 10. Calculate and display the score
quality_score = calculate_data_quality_score(df, total_issues)

print(f"Data Quality Score: {quality_score}")

Data Quality Score: 0

In [120]:
# 11. Save a dataset
def save_dataframe(df, file_path):
    if not df.empty:
        df.to_csv(file_path, index=False)
        print("Saved:", file_path)

In [115]:
print("\nDATA QUALITY REPORT")
print("---------------------")
print("Total rows:", len(df))
print("\nMissing values:")
print(missing_values)
print("Duplicate rows:", len(duplicate_rows))
print("Invalid Loan Amount:", len(invalid_loan_amount))
print("Invalid Interest Rate:", len(invalid_interest_rate))
print("Missing Borrower Name:", len(missing_borrower_name))
print("Invalid Loan Status:", len(invalid_loan_status))
print("Quality Score:", round(quality_score, 2), "%")

DATA QUALITY REPORT
---------------------
Total rows: 8

Missing values:
Loan_ID          0
Borrower_Name    1
Loan_Amount      1
Interest_Rate    1
Loan_Status      0
dtype: int64
Duplicate rows: 2
Invalid Loan Amount: 2
Invalid Interest Rate: 2
Missing Borrower Name: 1
Invalid Loan Status: 0
Quality Score: 0 %

In [116]:
# 12.Create a dictionary with the quality metrics
quality_metrics = {
    'Metric': ['Total rows', 'Duplicate rows', 'Invalid Loan Amount', 
               'Invalid Interest Rate', 'Missing Borrower Name', 
               'Invalid Loan Status', 'Quality Score'],
    'Value': [len(df), len(duplicate_rows), len(invalid_loan_amount),
              len(invalid_interest_rate), len(missing_borrower_name),
              len(invalid_loan_status), round(quality_score, 2)]
}

quality_metrics

{'Metric': ['Total rows',
  'Duplicate rows',
  'Invalid Loan Amount',
  'Invalid Interest Rate',
  'Missing Borrower Name',
  'Invalid Loan Status',
  'Quality Score'],
 'Value': [8, 2, 2, 2, 1, 0, 0]}

In [119]:
# 13. Convert the dictionary to a Dataframe
quality_output_report = pd.DataFrame(quality_metrics)

quality_output_report

                  Metric  Value
0             Total rows      8
1         Duplicate rows      2
2    Invalid Loan Amount      2
3  Invalid Interest Rate      2
4  Missing Borrower Name      1
5    Invalid Loan Status      0
6          Quality Score      0

In [121]:
# 14.Save the report as a text file
quality_output_report.to_csv('quality_metrics_report.txt', sep='\t', index=False)
with open('quality_metrics_report.txt', 'w') as f:
    f.write(quality_output_report.to_string())

print("Quality metrics report saved successfully!")

Quality metrics report saved successfully!